### PR TITLE
Support parsing of target frameworks so documentation can be generated for each target fx

### LINKED ISSUE #41: Support multiple frameworks (such as NET40, NET45, WIN81, etc)
I am considering to use this on a lot of projects that support multiple platforms (NET40, NET45, WP80, WP81, etc). What if it could create a section like MSDN does where the user can switch the target fx (some target fx don't have the same classes, although many are shared).

Then we can show that as the default on each page.

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
Fixes #41

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Will add the parsing to the types, then I think it's ready for a review.

**Comment by GeertvanHorrik** [comment]
@Geaz not sure about putting the SDTargetFx inside SDType. A type might be available for several target fxs, but they might differ / platform (some methods / docs are different based on the platform).

**Comment by GeertvanHorrik** [comment]
I think we should put the TargetFx inside SDRepository.

**Comment by Geaz** [comment]
Yes, I think this is the best position for it. But I think we have to to some more refactorings to get this working. Just try at and lets see :)

**Comment by GeertvanHorrik** [comment]
I am refactoring NRefactoryParser so it parsers / project instead of / solution. Then I think we have at least a workable data model.

**Comment by Geaz** [comment]
It should be able to parse both already!

**Comment by GeertvanHorrik** [comment]
But it should create a repository / project, not / solution. Digging into that right now.

**Comment by Geaz** [comment]
Wouldn't it be easier to have a List of SDTargetFxs on the SDType AND on the SDMember?
This way we get easily all available SDTargetFxs for one SDType and are able to save different SDMembers per SDTargetFx. Would this work?

I think this would make even the parsing a bit easier.

**Comment by GeertvanHorrik** [comment]
Yes, but not sure how the parser handles type it already handled before. Does it skip or fill the gap?

**Comment by Geaz** [comment]
It would fill the gap, but forget my comment. I think we would get some other problems with this solution...

**Comment by GeertvanHorrik** [comment]
Let me first finish the per project parsing, that would be easiest. Then we can create a reversed index to know what types / members are available for what target fx.

**Comment by GeertvanHorrik** [comment]
Testing the latest code now, I have a single repository / project (so we have all the info we need now). It doesn't hit performance (since we already parsed everything anyway). It will only have a negative impact on the memory (but I think the classes are pretty lightweight):

image

**Comment by GeertvanHorrik** [comment]
The html exporter needs some work I guess because it throws an exception that SDProject contains more than 1 instance of SDRepository, but I think the core parsing is all done now.

**Comment by Geaz** [comment]
Looks nice so far!
I am doing a complete html plugin rework at the moment and will look into this pr after I have done some major work on the new plugin. 

Thank you!

**Comment by Geaz** [comment]
I merged it now into the dev branch. Will do some further enhancements to get it fully working. Thank you!

**Pull request merged**
