### PR TITLE
Implementation of the SDPath class including unit tests

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
See #40

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Note that this PR is not yet done, but I wanted to see if you think I am on the right track and you are even interested in this feature.

**Comment by Geaz** [comment]
I wanted to replace this absolute path since a long time! So yes, I am interested :)
So far the implementation looks fine. Maybe you could use TrimStart and TrimEnd instead of your RemovingSlashes methods.

**Comment by GeertvanHorrik** [comment]
Yes, I implemented it in Catel a long time ago, just copy pasted the methods just fix see how you would respond to the PR. Will continue to work on it.

**Comment by GeertvanHorrik** [comment]
With the new code, the config will look like this:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<SDConfig>
  <section guid="feacbce2-8290-4d90-bb05-373b9d7dbbfc">
    <item key="ConfigFileName" value="Catel" />
    <PathToConfig>
      <Relative>catel.sdox</Relative>
      <Full>C:\Source\Catel\src\Catel.sdox</Full>
    </PathToConfig>
    <item key="LastBuild" value="18.5.2015 - 10:01" />
    <item key="ProjectName" value="Catel" />
    <item key="ProjectUrl" value="http://www.catelproject.com" />
    <item key="Author" value="CatenaLogic" />
    <InputFile>
      <Relative>catel.sln</Relative>
      <Full>C:\Source\Catel\src\Catel.sln</Full>
    </InputFile>
    <OutputPath>
      <Relative>..\..\..\users\geert\desktop\catel docs</Relative>
      <Full>C:\Users\Geert\Desktop\Catel docs</Full>
    </OutputPath>
    <item key="DocLanguage" value="en" />
    <item key="ExcludePrivate" value="True" />
    <item key="ExcludeProtected" value="False" />
    <item key="ExcludeInternal" value="False" />
    <item key="ActivatedExporters" value="Html" />
  </section>
</SDConfig>
```

Paths will be evaluated based on the directory. I set *Environment.CurrentDirectory* during load and save so we can always use that to resolve relative paths to the current path.

**Comment by GeertvanHorrik** [comment]
Resolving merge conflicts...

**Comment by GeertvanHorrik** [comment]
Everything should be resolved, please review this PR.

**Comment by Geaz** [comment]
Hi, looks fine so far. Unfortunately previous test are failing now.
I already know the cause. If you write a test like this:
```
SDPath testPath = null;
string testString = testPath;
```
it fails. If testPath is null i expect testString to be null, too. Instead I get a exception. Could you please check this?

**Comment by GeertvanHorrik** [comment]
Sorry, I should've run all tests. All should be working now.

**Comment by GeertvanHorrik** [comment]
Just in time, I was just about to create a new branch for the other PR. This saves me a lot of merge conflicts, thanks!

**Pull request merged**
